name: 'Validate NPM Package Version'
description: 'Ensure that the package version you want to publish is available'
inputs:
  auth-token:
    description: 'The token used for auth with the package registry'
    required: true
  scope:
    description: 'The scope to use with the package registry'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: 14
        registry-url: https://npm.pkg.github.com
        scope: ${{ inputs.scope }}
    - id: publish
      # this will only run if the PR has been merged and will not run if the PR was closed without being merged
      if: github.event.pull_request.merged == true
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}
    - id: release
      # this will only run if the PR has been merged and will not run if the PR was closed without being merged
      if: github.event.pull_request.merged == true
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        tag: ${{ steps.publish.outputs.version }}
