name: 'Validate NPM Package Version'
description: 'Ensure that the package version you want to publish is available'
inputs:
  github-token:
    description: 'The token used for auth with github'
    required: true
  package-registry-token:
    description: 'The token used for auth with the package registry'
    required: true
  scope:
    description: 'The scope to use with the package registry'
    required: false
  version-prefix:
    description: 'A prefix that will be prepended to the version.  E.g. in v1.0.0 the prefix is "v"'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
